sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t jah786/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jah786/docker-react npm run test
